INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('CIBa100', 'Bacharelado em Ciência da Computação', 'CI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('CIEn101', 'Engenharia de Software', 'CI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('CISi102', 'Sistemas de Informação', 'CI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('CIIn103', 'Inteligência Artificial Aplicada', 'CI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('CISe104', 'Segurança da Informação', 'CI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('CIDe105', 'Desenvolvimento de Jogos Digitais', 'CI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('CICo106', 'Computação em Nuvem', 'CI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('CICi107', 'Ciência de Dados', 'CI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('CIRe108', 'Redes de Computadores', 'CI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('CITe109', 'Tecnologia da Informação Biomédica', 'CI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MALi110', 'Licenciatura em Matemática', 'MA');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MAMa111', 'Matemática Aplicada à Economia', 'MA');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MAEs112', 'Estatística e Probabilidade', 'MA');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MAMa113', 'Matemática Financeira', 'MA');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MAMo114', 'Modelagem Matemática', 'MA');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MATe115', 'Teoria dos Números', 'MA');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MAGe116', 'Geometria Diferencial', 'MA');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MAAn117', 'Análise Matemática Avançada', 'MA');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LETo118', 'Topologia', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LELe119', 'Letras - Português e Inglês', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LELe120', 'Letras - Português e Espanhol', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LELe121', 'Letras - Português e Francês', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LELe122', 'Letras - Português e Alemão', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LETr123', 'Tradução e Interpretação', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LELi124', 'Linguística Aplicada', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LEEs125', 'Estudos Literários', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LEEs126', 'Escrita Criativa', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LETe127', 'Teoria da Tradução', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('LELe128', 'Lexicografia', 'LE');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ADAd129', 'Administração de Empresas', 'AD');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ADGe130', 'Gestão de Recursos Humanos', 'AD');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ADAd131', 'Administração Financeira', 'AD');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ADMa132', 'Marketing e Publicidade', 'AD');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ADLo133', 'Logística e Supply Chain Management', 'AD');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ADEm134', 'Empreendedorismo', 'AD');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ADGe135', 'Gestão de Projetos', 'AD');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ADCo136', 'Consultoria Empresarial', 'AD');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ADGe137', 'Gestão de Negócios Internacionais', 'AD');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ADAd138', 'Administração Pública', 'AD');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('PSPs139', 'Psicologia Clínica', 'PS');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('PSPs140', 'Psicologia Organizacional', 'PS');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('PSPs141', 'Psicologia Social', 'PS');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('PSNe142', 'Neuropsicologia', 'PS');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('PSPs143', 'Psicologia do Desenvolvimento', 'PS');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('PSPs144', 'Psicologia do Esporte', 'PS');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('PSPs145', 'Psicologia da Saúde', 'PS');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('PSPs146', 'Psicologia Forense', 'PS');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('PSPs147', 'Psicologia Transpessoal', 'PS');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('BIBi148', 'Biologia Celular e Molecular', 'BI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('BIBi149', 'Biologia Marinha', 'BI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('BIEc150', 'Ecologia', 'BI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('BIZo151', 'Zoologia', 'BI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('BIMi152', 'Microbiologia', 'BI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('BIBi153', 'Biologia do Desenvolvimento', 'BI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('BIBi154', 'Biologia Ambiental', 'BI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('BIBi155', 'Biomedicina', 'BI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ENEn156', 'Engenharia Civil', 'EN');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ENEn157', 'Engenharia Mecânica', 'EN');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ENEn158', 'Engenharia Elétrica', 'EN');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ENEn159', 'Engenharia de Produção', 'EN');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ENEn160', 'Engenharia Química', 'EN');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ENEn161', 'Engenharia de Telecomunicações', 'EN');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ENEn162', 'Engenharia Ambiental', 'EN');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ENEn163', 'Engenharia de Computação', 'EN');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ENEn164', 'Engenharia de Alimentos', 'EN');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ENEn165', 'Engenharia Aeroespacial', 'EN');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ARAr166', 'Artes Plásticas', 'AR');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ARDe167', 'Design Gráfico', 'AR');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ARFo168', 'Fotografia e Imagem Digital', 'AR');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ARCi169', 'Cinema e Audiovisual', 'AR');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ARHi170', 'História da Arte', 'AR');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ARAr171', 'Arte Educação', 'AR');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ARIl172', 'Ilustração e Animação', 'AR');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ARCo173', 'Conservação e Restauração de Obras de Arte', 'AR');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ARAr174', 'Arte Contemporânea', 'AR');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DICu175', 'Curadoria e Gestão Cultural', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DIDi176', 'Direito Civil', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DIDi177', 'Direito Penal', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DIDi178', 'Direito Constitucional', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DIDi179', 'Direito Tributário', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DIDi180', 'Direito do Trabalho', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DIDi181', 'Direito Internacional', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DIDi182', 'Direito Ambiental', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DIDi183', 'Direitos Humanos', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DIMe184', 'Mediação e Arbitragem', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('DIDi185', 'Direito Empresarial', 'DI');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MEMe186', 'Medicina Geral', 'ME');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MECi187', 'Cirurgia Geral', 'ME');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MEPe188', 'Pediatria', 'ME');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MEGi189', 'Ginecologia e Obstetrícia', 'ME');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MECa190', 'Cardiologia', 'ME');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MENe191', 'Neurologia', 'ME');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MEOr192', 'Ortopedia', 'ME');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MEOn193', 'Oncologia', 'ME');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MEDe194', 'Dermatologia', 'ME');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('MEPs195', 'Psiquiatria', 'ME');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ECEc196', 'Economia Aplicada', 'EC');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ECEc197', 'Economia Internacional', 'EC');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ECEc198', 'Economia do Desenvolvimento', 'EC');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ECFi199', 'Finanças Corporativas', 'EC');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ECEc200', 'Economia Comportamental', 'EC');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ECPo201', 'Políticas Públicas', 'EC');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ECEc202', 'Economia Agrícola', 'EC');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ECEc203', 'Economia da Saúde', 'EC');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ECEc204', 'Economia Ambiental', 'EC');
INSERT INTO Curso (id_curso, nome_curso, id_dept) VALUES ('ECEc205', 'Economia Monetária', 'EC');
