insert into Departamento (id_dept, nome_dept, id_chefe) values ('CI', 'Departamento de Ciências da Computação', '748146844');
insert into Departamento (id_dept, nome_dept, id_chefe) values ('MA', 'Departamento de Matemática', '377276899');
insert into Departamento (id_dept, nome_dept, id_chefe) values ('LE', 'Departamento de Letras', '539191469');
insert into Departamento (id_dept, nome_dept, id_chefe) values ('AS', 'Departamento de Administração', '683936993');
insert into Departamento (id_dept, nome_dept, id_chefe) values ('PS', 'Departamento de Psicologia', '816398345');
insert into Departamento (id_dept, nome_dept, id_chefe) values ('BI', 'Departamento de Biologia', '678591153');
insert into Departamento (id_dept, nome_dept, id_chefe) values ('EN', 'Departamento de Engenharias', '292847945');
insert into Departamento (id_dept, nome_dept, id_chefe) values ('AR', 'Departamento de Artes Visuais', '399664635');
insert into Departamento (id_dept, nome_dept, id_chefe) values ('DI', 'Departamento de Direito', '332515345');
insert into Departamento (id_dept, nome_dept, id_chefe) values ('ME', 'Departamento de Medicina', '778873933');
insert into Departamento (id_dept, nome_dept, id_chefe) values ('EC', 'Departamento de Economia', '121854349');
