insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI10', 'Matemática', 'CI', '748146844');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI11', 'Física', 'MA', '377276899');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI12', 'Química', 'LE', '539191469');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI13', 'Biologia', 'AS', '683936993');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI14', 'História', 'PS', '816398345');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI15', 'Geografia', 'PS', '678591153');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI16', 'Literatura', 'BI', '292847945');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI17', 'Filosofia', 'BI', '399664635');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI18', 'Sociologia', 'PS', '332515345');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI19', 'Psicologia', 'EN', '778873933');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI20', 'Economia', 'AR', '121854349');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI21', 'Engenharia', 'LE', '211513559');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI22', 'Medicina', 'DI', '168248723');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI23', 'Direito', 'AS', '681757547');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI24', 'Arquitetura', 'DI', '613843612');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI25', 'Informática', 'MA', '295315977');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI26', 'Estatística', 'ME', '843676127');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI27', 'Filosofia', 'DI', '176183812');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI28', 'Educação Física', 'EN', '987163614');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI29', 'Artes', 'AS', '539183549');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI30', 'Música', 'PS', '335511351');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI31', 'Teatro', 'CI', '224631614');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI32', 'Cinema', 'PS', '748146844');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI33', 'Fotografia', 'PS', '377276899');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI34', 'Design', 'EN', '539191469');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI35', 'Moda', 'PS', '683936993');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI36', 'Gastronomia', 'MA', '816398345');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI37', 'Nutrição', 'ME', '678591153');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI38', 'Veterinária', 'EN', '292847945');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI39', 'Zootecnia', 'CI', '399664635');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI40', 'Agronomia', 'MA', '332515345');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI41', 'Farmácia', 'AR', '778873933');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI42', 'Enfermagem', 'MA', '121854349');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI43', 'Odontologia', 'DI', '211513559');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI44', 'Fisioterapia', 'AS', '168248723');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI45', 'Biomedicina', 'PS', '681757547');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI46', 'Educação Especial', 'MA', '613843612');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI47', 'Administração', 'PS', '295315977');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI48', 'Marketing', 'CI', '843676127');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI49', 'Recursos Humanos', 'LE', '176183812');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI50', 'Contabilidade', 'MA', '987163614');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI51', 'Relações Internacionais', 'LE', '539183549');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI52', 'Gastronomia', 'PS', '335511351');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI53', 'Logística', 'BI', '224631614');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI54', 'Turismo', 'LE', '748146844');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI55', 'Eventos', 'PS', '377276899');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI56', 'Esportes', 'DI', '539191469');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI57', 'Dança', 'ME', '683936993');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI58', 'Educação Infantil', 'EC', '816398345');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI59', 'Pedagogia', 'PS', '678591153');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI60', 'Ciências Sociais', 'EN', '292847945');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI61', 'Antropologia', 'CI', '399664635');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI62', 'Arqueologia', 'AS', '332515345');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI63', 'Arquivologia', 'MA', '778873933');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI64', 'Museologia', 'DI', '121854349');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI65', 'Biblioteconomia', 'EC', '211513559');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI66', 'Ciências Atuariais', 'CI', '168248723');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI67', 'Ciências Contábeis', 'BI', '681757547');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI68', 'Ciências Econômicas', 'LE', '613843612');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI69', 'Ciências Biológicas', 'DI', '295315977');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI70', 'Biotecnologia', 'PS', '843676127');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI71', 'Física Médica', 'EN', '176183812');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI72', 'Genética', 'AS', '987163614');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI73', 'Geofísica', 'AR', '539183549');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI74', 'Geologia', 'DI', '335511351');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI75', 'Meteorologia', 'EC', '224631614');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI76', 'Oceanografia', 'AS', '748146844');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI77', 'Química Industrial', 'BI', '377276899');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI78', 'Engenharia Civil', 'AS', '539191469');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI79', 'Engenharia Elétrica', 'DI', '683936993');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI80', 'Engenharia Mecânica', 'EC', '816398345');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI81', 'Engenharia Química', 'PS', '678591153');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI82', 'Engenharia de Produção', 'CI', '292847945');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI83', 'Engenharia de Alimentos', 'AR', '399664635');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA10', 'Engenharia de Software', 'DI', '332515345');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA11', 'Sistemas de Informação', 'DI', '778873933');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA12', 'Ciência da Computação', 'MA', '121854349');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA13', 'Engenharia da Computação', 'AS', '211513559');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA14', 'Análise de Sistemas', 'AR', '168248723');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA15', 'Redes de Computadores', 'PS', '681757547');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA16', 'Segurança da Informação', 'BI', '613843612');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA17', 'Inteligência Artificial', 'DI', '295315977');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA18', 'Robótica', 'MA', '843676127');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA19', 'Banco de Dados', 'BI', '176183812');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA20', 'Desenvolvimento Web', 'EN', '987163614');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA21', 'Desenvolvimento de Jogos', 'AR', '539183549');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA22', 'Computação Gráfica', 'AS', '335511351');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA23', 'Processamento de Imagens', 'CI', '224631614');
