insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI10', 'Matemática', 'CI', '748146844');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI11', 'Física', 'MA', '377276899');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI12', 'Química', 'LE', '539191469');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI13', 'Biologia', 'AS', '683936993');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI14', 'História', 'PS', '816398345');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI15', 'Geografia', 'PS', '678591153');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI16', 'Literatura', 'BI', '292847945');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI17', 'Filosofia', 'BI', '399664635');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI18', 'Sociologia', 'PS', '332515345');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI19', 'Psicologia', 'EN', '778873933');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI20', 'Economia', 'AR', '121854349');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI21', 'Engenharia', 'LE', '211513559');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI22', 'Medicina', 'DI', '168248723');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI23', 'Direito', 'AS', '681757547');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI24', 'Arquitetura', 'DI', '613843612');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI25', 'Informática', 'MA', '295315977');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI26', 'Estatística', 'ME', '843676127');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI27', 'Filosofia', 'DI', '176183812');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI28', 'Educação Física', 'EN', '987163614');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI29', 'Artes', 'AS', '539183549');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI30', 'Música', 'PS', '335511351');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI31', 'Teatro', 'CI', '224631614');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI32', 'Cinema', 'PS', '428762395');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI33', 'Fotografia', 'PS', '431592989');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI34', 'Design', 'EN', '295284587');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI35', 'Moda', 'PS', '758752149');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI36', 'Gastronomia', 'MA', '875756749');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI37', 'Nutrição', 'ME', '487792796');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI38', 'Veterinária', 'EN', '293674128');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI39', 'Zootecnia', 'CI', '116221315');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI40', 'Agronomia', 'MA', '417461132');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI41', 'Farmácia', 'AR', '348949534');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI42', 'Enfermagem', 'MA', '444556638');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI43', 'Odontologia', 'DI', '458648175');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI44', 'Fisioterapia', 'AS', '668477713');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI45', 'Biomedicina', 'PS', '428812749');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI46', 'Educação Especial', 'MA', '936742514');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI47', 'Administração', 'PS', '324742238');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI48', 'Marketing', 'CI', '579285691');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI49', 'Recursos Humanos', 'LE', '511796375');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI50', 'Contabilidade', 'MA', '257573214');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI51', 'Relações Internacionais', 'LE', '175116192');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI52', 'Gastronomia', 'PS', '497518991');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI53', 'Logística', 'BI', '867769665');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI54', 'Turismo', 'LE', '738245829');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI55', 'Eventos', 'PS', '424988428');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI56', 'Esportes', 'DI', '981247616');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI57', 'Dança', 'ME', '389875862');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI58', 'Educação Infantil', 'EC', '624798529');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI59', 'Pedagogia', 'PS', '871814144');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI60', 'Ciências Sociais', 'EN', '664636146');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI61', 'Antropologia', 'CI', '271734286');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI62', 'Arqueologia', 'AS', '357226722');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI63', 'Arquivologia', 'MA', '886195539');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI64', 'Museologia', 'DI', '575733867');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI65', 'Biblioteconomia', 'EC', '659246753');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI66', 'Ciências Atuariais', 'CI', '954327984');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI67', 'Ciências Contábeis', 'BI', '231186657');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI68', 'Ciências Econômicas', 'LE', '174266995');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI69', 'Ciências Biológicas', 'DI', '948322524');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI70', 'Biotecnologia', 'PS', '773915569');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI71', 'Física Médica', 'EN', '767263733');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI72', 'Genética', 'AS', '288958745');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI73', 'Geofísica', 'AR', '183936948');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI74', 'Geologia', 'DI', '355125729');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI75', 'Meteorologia', 'EC', '734259378');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI76', 'Oceanografia', 'AS', '796765554');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI77', 'Química Industrial', 'BI', '481939243');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI78', 'Engenharia Civil', 'AS', '356736427');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI79', 'Engenharia Elétrica', 'DI', '259339327');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI80', 'Engenharia Mecânica', 'EC', '522884198');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI81', 'Engenharia Química', 'PS', '952119654');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI82', 'Engenharia de Produção', 'CI', '962587571');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('CI83', 'Engenharia de Alimentos', 'AR', '628428823');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA10', 'Engenharia de Software', 'DI', '657193551');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA11', 'Sistemas de Informação', 'DI', '456447465');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA12', 'Ciência da Computação', 'MA', '166745888');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA13', 'Engenharia da Computação', 'AS', '722132241');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA14', 'Análise de Sistemas', 'AR', '625449498');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA15', 'Redes de Computadores', 'PS', '936594725');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA16', 'Segurança da Informação', 'BI', '241277899');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA17', 'Inteligência Artificial', 'DI', '863448183');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA18', 'Robótica', 'MA', '577569836');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA19', 'Banco de Dados', 'BI', '377862678');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA20', 'Desenvolvimento Web', 'EN', '915287824');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA21', 'Desenvolvimento de Jogos', 'AR', '362586644');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA22', 'Computação Gráfica', 'AS', '359832974');
insert into Disciplinas (id_disc, nome_disc, id_dept, prof_id) values ('MA23', 'Processamento de Imagens', 'CI', '198472261');
