insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('748146844', 1, 'Análise de Algoritmos de Ordenação');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('377276899', 2, 'Desenvolvimento de Aplicações Web com Python');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('539191469', 3, 'O Impacto da IA na Medicina');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('683936993', 4, 'Sistemas de Recomendação em E-commerce');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('816398345', 5, 'Segurança em Redes de Computadores');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('678591153', 6, 'Big Data e Análise de Dados');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('292847945', 7, 'Machine Learning para Previsão de Vendas');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('399664635', 8, 'Blockchain e Criptomoedas');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('332515345', 9, 'Desenvolvimento de Jogos com Unity');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('778873933', 10, 'Redes Neurais e Deep Learning');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('121854349', 11, 'Realidade Aumentada em Aplicativos Educacionais');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('211513559', 12, 'Sistemas de Controle para Robôs Autônomos');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('168248723', 13, 'Reconhecimento de Voz com Técnicas de IA');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('681757547', 14, 'Aplicações de IoT na Agricultura');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('613843612', 15, 'Automação Residencial com Arduino');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('295315977', 16, 'Sistemas de Informação Geográfica');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('843676127', 17, 'Visão Computacional para Identificação de Imagens');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('176183812', 18, 'Desenvolvimento de Assistentes Virtuais');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('987163614', 19, 'Computação Quântica: Princípios e Aplicações');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('539183549', 20, 'Modelagem e Simulação de Sistemas Dinâmicos');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('335511351', 21, 'Sistemas Distribuídos e Cloud Computing');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('224631614', 22, 'Bioinformática e Análise Genômica');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('428762395', 23, 'Desenvolvimento de Chatbots Inteligentes');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('431592989', 24, 'Algoritmos Genéticos em Otimização');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('295284587', 25, 'Criação de Aplicativos Móveis com Flutter');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('758752149', 26, 'Engenharia de Software Ágil');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('875756749', 27, 'Processamento de Imagens Médicas');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('487792796', 28, 'Aplicações de Realidade Virtual na Educação');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('293674128', 29, 'Desenvolvimento de Sistemas de Gestão Empresarial');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('116221315', 30, 'Inteligência Artificial em Jogos');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('417461132', 31, 'Estudo de Protocolos de Comunicação em IoT');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('348949534', 32, 'Plataformas de Computação em Nuvem');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('444556638', 33, 'Aplicações de Biometria em Segurança');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('458648175', 34, 'Desenvolvimento de Sistemas Embarcados');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('668477713', 35, 'Reconhecimento Facial com Deep Learning');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('428812375', 36, 'Análise de Redes Sociais com Data Mining');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('457392551', 37, 'Processamento de Linguagem Natural');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('757131522', 38, 'Desenvolvimento de Aplicativos com React Native');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('577913883', 39, 'Sistemas de Apoio à Decisão');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('392278569', 40, 'Robótica Educacional para Crianças');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('749277582', 41, 'Desenvolvimento de Sistemas para IoT');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('527835337', 42, 'Segurança da Informação em Empresas');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('358732864', 43, 'Aplicações de Inteligência Artificial em Saúde');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('428592551', 44, 'Desenvolvimento de APIs RESTful');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('223512851', 45, 'Gestão de Projetos de TI');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('459182373', 46, 'Desenvolvimento de Softwares Educacionais');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('417181539', 47, 'Sistemas de Automação Industrial');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('228597124', 48, 'Aplicações de Sensores em Agricultura de Precisão');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('459283591', 49, 'Desenvolvimento de Assistentes Pessoais com IA');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('681789251', 50, 'Reconhecimento de Padrões em Imagens');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('348592751', 51, 'Sistemas de Monitoramento de Saúde');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('229789537', 52, 'Automação de Processos com Robotic Process Automation');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('528923875', 53, 'Desenvolvimento de Jogos Educativos');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('428395721', 54, 'Implementação de Algoritmos de Machine Learning');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('717812534', 55, 'Análise de Dados com Ferramentas de BI');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('512389573', 56, 'Desenvolvimento de Sistemas de E-commerce');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('598731628', 57, 'Estudo de Redes de Sensores Sem Fio');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('428981753', 58, 'Plataformas de Ensino a Distância');
insert into Grupo_TCC (id_tcc, prof_id, titulo) values ('239851473', 59, 'Desenvolvimento de Sistemas de Informação');
